name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  javac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "oracle"
      - run: |
          javac -d bin src/*.java
          jar cfe bin/Snakewing.jar Main -C bin .
